### ISSUE TITLE
Unify Pro SmartAudioV2

### ISSUE THREAD

**Issue by Machtap** [gregorg/KISS_OSD#9]
https://github.com/betaflight/betaflight/files/430302/TBS.SmartAudio.Rev07.pdf

Is there any way support for vTX configuration (and pitmode etc.) could be implemented for use with this OSD firmware on a micro-minim?

If so, what can I do to help make it happen?

**Comment by gregorg** [comment]
There is no way to implement this on this osd, but ask ShikOfTheRa and his osd https://github.com/ShikOfTheRa/scarab-osd
